swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: sendmail
    auth_mode: login
    port: 465
    host: smtp.ionos.fr
    username: alexandre.desmot@otoktone.fr
    password: umamd*5tv.F%S*e
    spool: { type: 'memory' }
